use hl3265;
insert into word (word, part_id, definition) values ("abate", 4, "to put an end to; nullify");
insert into word (word, part_id, definition) values ("abeyance", 3, "a lapse in succession during which there is no person in whom a title is vested");
insert into word (word, part_id, definition) values ("abjure", 4, "to renounce upon oath; to reject solemnly");
insert into word (word, part_id, definition) values ("abrogate", 4, "to abolish by authoritative action; annul");
insert into word (word, part_id, definition) values ("abstruse", 1, "difficult to comprehend; obscure");
insert into word (word, part_id, definition) values ("acarpous", 1, "effete; no longer fertile; worn out");
insert into word (word, part_id, definition) values ("accretion", 3, "the process of growth or enlargement by a gradual buildup; increase by external addition or accumulation (as by adhesion of external parts or particles); the increase of land by the action of natural forces");
insert into word (word, part_id, definition) values ("agog", 1, "full of intense interest or excitement; eager");
insert into word (word, part_id, definition) values ("alloy", 3, "the mixture of disparate elements");
insert into word (word, part_id, definition) values ("amortize", 4, "to pay off (as a mortgage) gradually, usually by periodic payments of principal and interest or by payments to a sinking fund");
insert into word (word, part_id, definition) values ("aplomb", 3, "complete and confident composure or self-assurance; poise");
insert into word (word, part_id, definition) values ("apostasy", 3, "renunciation of a religious faith");
insert into word (word, part_id, definition) values ("apostate", 3, "one who abandons long-held religious or political convictions");
insert into word (word, part_id, definition) values ("apposite", 1, "highly pertinent, relevant, or appropriate");
insert into word (word, part_id, definition) values ("approbation", 3, "approval");
insert into word (word, part_id, definition) values ("arabesque", 1, "Arabian in fashion");
insert into word (word, part_id, definition) values ("argot", 3, "an often more or less secret vocabulary and idiom peculiar to a particular group");
insert into word (word, part_id, definition) values ("ascetic", 1, "practicing strict self-denial as a measure of personal and especially spiritual discipline");
insert into word (word, part_id, definition) values ("asperity", 3, "rigor, severity");
insert into word (word, part_id, definition) values ("assiduous", 1, "marked by careful unremitting attention or persistent application");
insert into word (word, part_id, definition) values ("astringent", 1, "causing contraction of soft organic tissues; styptic, puckery");
insert into word (word, part_id, definition) values ("augury", 3, "omen sign");
insert into word (word, part_id, definition) values ("aver", 4, "to verify or prove to be true in pleading a cause; to allege or assert in pleading");
insert into word (word, part_id, definition) values ("baleful", 1, "harmful ominous causing evil");
insert into word (word, part_id, definition) values ("beatific", 1, "of, possessing, or imparting beatitude");
insert into word (word, part_id, definition) values ("beatify", 4, "to make supremely happy");
insert into word (word, part_id, definition) values ("bedizen", 4, "to adorn especially in a cheap showy manner");
insert into word (word, part_id, definition) values ("bellicose", 1, "favoring or inclined to start quarrels or wars");
insert into word (word, part_id, definition) values ("benign", 1, "of a gentle disposition; gracious");
insert into word (word, part_id, definition) values ("benison", 3, "blessing, benediction");
insert into word (word, part_id, definition) values ("bequest", 3, "the act of bequeathing");
insert into word (word, part_id, definition) values ("blandishment", 3, "flattery coaxing");
insert into word (word, part_id, definition) values ("blithe", 1, "of a happy lighthearted character or disposition");
insert into word (word, part_id, definition) values ("bombastic", 1, "overblown");
insert into word (word, part_id, definition) values ("burnish", 4, "to make shiny or lustrous especially by rubbing; polish");
insert into word (word, part_id, definition) values ("cajole", 4, "to persuade with flattery or gentle urging especially in the face of reluctance; coax; to obtain from someone by gentle persuasion");
insert into word (word, part_id, definition) values ("calumny", 3, "a misrepresentation intended to harm another's reputation");
insert into word (word, part_id, definition) values ("capricious", 1, "unpredictable; fickle");
insert into word (word, part_id, definition) values ("castigate", 4, "to subject to severe punishment, reproof, or criticism");
insert into word (word, part_id, definition) values ("censure", 3, "a judgment involving condemnation");
insert into word (word, part_id, definition) values ("chaff", 3, "the seed coverings and other debris separated from the seed in threshing grain");
insert into word (word, part_id, definition) values ("chary", 1, "discreetly cautious; hesitant and vigilant about dangers and risks; slow to grant, accept, or expend");
insert into word (word, part_id, definition) values ("chicanery", 3, "legal trickery or false argument");
insert into word (word, part_id, definition) values ("churlish", 1, "marked by a lack of civility or graciousness");
insert into word (word, part_id, definition) values ("cloture", 3, "the closing or limitation of debate in a legislative body especially by calling for a vote");
insert into word (word, part_id, definition) values ("coda", 3, "a concluding musical section that is formally distinct from the main structure; a concluding part of a literary or dramatic work");
insert into word (word, part_id, definition) values ("coeval", 1, "of the same or equal age, antiquity, or duration");
insert into word (word, part_id, definition) values ("cogent", 1, "having power to compel or constrain");
insert into word (word, part_id, definition) values ("collusion", 3, "secret agreement or cooperation especially for an illegal or deceitful purpose");
insert into word (word, part_id, definition) values ("commodious", 1, "comfortably or conveniently spacious; roomy");
insert into word (word, part_id, definition) values ("complaisance", 3, "tending to comply obliging willingness to please");
insert into word (word, part_id, definition) values ("compunction", 3, "anxiety arising from awareness of guilt; distress of mind over an anticipated action or result");
insert into word (word, part_id, definition) values ("concord", 3, "a state of agreement; harmony; a simultaneous occurrence of two or more musical tones that produces an impression of agreeableness or resolution on a listener");
insert into word (word, part_id, definition) values ("contemn", 4, "to view or treat with contempt; scorn");
insert into word (word, part_id, definition) values ("continent", 1, "exercising continence");
insert into word (word, part_id, definition) values ("contumacious", 1, "insubordinate; rebellious");
insert into word (word, part_id, definition) values ("convoke", 4, "to call together to a meeting");
insert into word (word, part_id, definition) values ("cornucopia", 3, "abundant supply");
insert into word (word, part_id, definition) values ("corporeal", 1, "having, consisting of, or relating to a physical material body; not spiritual; not immaterial or intangible; substantial");
insert into word (word, part_id, definition) values ("craven", 1, "lacking the least bit of courage; contemptibly fainthearted");
insert into word (word, part_id, definition) values ("credulous", 1, "ready to believe especially on slight or uncertain evidence");
insert into word (word, part_id, definition) values ("cursory", 1, "rapidly and often superficially performed or produced; hasty");
insert into word (word, part_id, definition) values ("dapper", 1, "neat and trim in appearance; very spruce and stylish");
insert into word (word, part_id, definition) values ("dastard", 3, "coward");
insert into word (word, part_id, definition) values ("dearth", 3, "an inadequate supply; lack");
insert into word (word, part_id, definition) values ("decry", 4, "to depreciate officially or publicly");
insert into word (word, part_id, definition) values ("delineate", 4, "to indicate or represent by drawn or painted lines; to mark the outline of");
insert into word (word, part_id, definition) values ("demagogue", 3, "a leader who makes use of popular prejudices and false claims and promises in order to gain power");
insert into word (word, part_id, definition) values ("denouement", 3, "the final outcome of the main dramatic complication in a literary work");
insert into word (word, part_id, definition) values ("desiccant", 3, "substance used to absorb moisture");
insert into word (word, part_id, definition) values ("desultory", 1, "marked by lack of definite plan, regularity, or purpose");
insert into word (word, part_id, definition) values ("detumescence", 3, "subsidence or diminution of swelling or erection");
insert into word (word, part_id, definition) values ("diaphanous", 1, "characterized by such fineness of texture as to permit seeing through");
insert into word (word, part_id, definition) values ("diffidence", 3, "shyness");
insert into word (word, part_id, definition) values ("dilatory", 1, "tending or intended to cause delay");
insert into word (word, part_id, definition) values ("discomfit", 4, "to put into a state of perplexity and embarrassment; disconcert");
insert into word (word, part_id, definition) values ("discountenance", 4, "refuse to approve of");
insert into word (word, part_id, definition) values ("disingenuous", 1, "sophisticated artful trying to deceive cunning");
insert into word (word, part_id, definition) values ("dissemble", 4, "to hide under a false appearance");
insert into word (word, part_id, definition) values ("dissolute", 1, "unrestrained by convention or morality");
insert into word (word, part_id, definition) values ("divestiture", 3, "the act of divesting");
insert into word (word, part_id, definition) values ("doggerel", 3, "a clumsy or poorly crafted verse of irregular measure");
insert into word (word, part_id, definition) values ("droll", 1, "having a humorous, whimsical, or odd quality");
insert into word (word, part_id, definition) values ("dulcet", 1, "sweet to the taste");
insert into word (word, part_id, definition) values ("ebullience", 3, "exuberance outburst of feeling");
insert into word (word, part_id, definition) values ("ecumenical", 1, "worldwide or general in extent, influence, or application");
insert into word (word, part_id, definition) values ("edacious", 1, "voracious");
insert into word (word, part_id, definition) values ("effete", 1, "no longer fertile");
insert into word (word, part_id, definition) values ("effluvia", 3, "a by-product especially in the form of waste");
insert into word (word, part_id, definition) values ("effrontery", 3, "shameless boldness; insolence");
insert into word (word, part_id, definition) values ("effulgent", 3, "radiant splendor; brilliance");
insert into word (word, part_id, definition) values ("egress", 3, "the action of going or coming out");
insert into word (word, part_id, definition) values ("elegiac", 1, "of, relating to, or consisting of two dactylic hexameter lines the second of which lacks the arsis in the third and sixth feet; written in or consisting of elegiac couplets; noted for having written poetry in such couplets; of or relating to the period in Greece about the seventh century B.C. when poetry written in such couplets flourished");
insert into word (word, part_id, definition) values ("emaciate", 4, "to cause to lose flesh so as to become very thin");
insert into word (word, part_id, definition) values ("encomium", 3, "a formal expression of praise");
insert into word (word, part_id, definition) values ("endemic", 1, "belonging or native to a particular people or country; characteristic of or prevalent in a particular field, area, or environment");
insert into word (word, part_id, definition) values ("enervate", 1, "weaken deprive of strength attenuate");
insert into word (word, part_id, definition) values ("enthral", 4, "to hold in or reduce to slavery");
insert into word (word, part_id, definition) values ("epistle", 3, "a specially long, formal letter");
insert into word (word, part_id, definition) values ("epithet", 3, "a characterizing word or phrase accompanying or occurring in place of the name of a person or thing; a disparaging or abusive word or phrase; the part of a taxonomic name identifying a subordinate unit within a genus");
insert into word (word, part_id, definition) values ("equable", 1, "marked by lack of variation or change; uniform");
insert into word (word, part_id, definition) values ("equanimity", 3, "evenness of mind especially under stress");
insert into word (word, part_id, definition) values ("equipoise", 3, "equal distribution of weight equilibrium");
insert into word (word, part_id, definition) values ("equivocal", 1, "subject to two or more interpretations and usually used to mislead or confuse; uncertain as an indication or sign");
insert into word (word, part_id, definition) values ("equivocate", 4, "try to deceive by equivocal language");
insert into word (word, part_id, definition) values ("erudite", 1, "possessing or displaying erudition; learned");
insert into word (word, part_id, definition) values ("euphonious", 1, "pleasing to the ear");
insert into word (word, part_id, definition) values ("evince", 4, "to constitute outward evidence of");
insert into word (word, part_id, definition) values ("excoriate", 4, "to wear off the skin of; abrade");
insert into word (word, part_id, definition) values ("excoriation", 4, "to wear off the skin of; abrade");
insert into word (word, part_id, definition) values ("exculpate", 4, "to clear from alleged fault or guilt");
insert into word (word, part_id, definition) values ("exigent", 1, "requiring immediate aid or action");
insert into word (word, part_id, definition) values ("exorbitant", 1, "not coming within the scope of the law");
insert into word (word, part_id, definition) values ("expiation", 3, "ending expiring");
insert into word (word, part_id, definition) values ("exscind", 4, "to cut off or out; excise");
insert into word (word, part_id, definition) values ("extant", 1, "currently or actually existing; still existing; not destroyed or lost");
insert into word (word, part_id, definition) values ("extirpate", 4, "to destroy completely; wipe out; to pull up by the root");
insert into word (word, part_id, definition) values ("fatuous", 1, "complacently or inanely foolish; silly");
insert into word (word, part_id, definition) values ("feckless", 1, "weak, ineffective");
insert into word (word, part_id, definition) values ("fecund", 1, "fruitful in offspring or vegetation; prolific");
insert into word (word, part_id, definition) values ("felicity", 3, "something that causes happiness");
insert into word (word, part_id, definition) values ("fervid", 1, "very hot; burning");
insert into word (word, part_id, definition) values ("fetter", 3, "a chain or shackle for the feet");
insert into word (word, part_id, definition) values ("finical", 1, "exacting, especially about details; finicky");
insert into word (word, part_id, definition) values ("flax", 3, "the fiber of the flax plant especially when prepared for spinning");
insert into word (word, part_id, definition) values ("florid", 1, "tinged with red; ruddy; marked by emotional or sexual fervor");
insert into word (word, part_id, definition) values ("foible", 3, "the part of a sword blade between the middle and point");
insert into word (word, part_id, definition) values ("foppish", 1, "like a man who pays too much attention to his clothes");
insert into word (word, part_id, definition) values ("forbearance", 3, "patience willingness to wait");
insert into word (word, part_id, definition) values ("forswear", 4, "to make a liar of (oneself) under or as if under oath");
insert into word (word, part_id, definition) values ("frenetic", 1, "frenzied, frantic");
insert into word (word, part_id, definition) values ("froward", 1, "habitually disposed to disobedience and opposition");
insert into word (word, part_id, definition) values ("fulmination", 3, "thunderous verbal attack with noise and violence");
insert into word (word, part_id, definition) values ("gaucherie", 3, "a tactless or awkward act");
insert into word (word, part_id, definition) values ("germane", 1, "being at once relevant and appropriate; fitting");
insert into word (word, part_id, definition) values ("glib", 1, "marked by ease and informality; nonchalant; showing little forethought or preparation; offhand; lacking depth and substance; superficial");
insert into word (word, part_id, definition) values ("glut", 4, "to fill especially with food to satiety");
insert into word (word, part_id, definition) values ("goad", 3, "something that pains as if by pricking; thorn; something that urges or stimulates into action; spur");
insert into word (word, part_id, definition) values ("gossamer", 3, "a film of cobwebs floating in air in calm clear weather");
insert into word (word, part_id, definition) values ("grandiloquent", 3, "a lofty, extravagantly colorful, pompous, or bombastic style, manner, or quality especially in language");
insert into word (word, part_id, definition) values ("gregarious", 1, "tending to associate with others of one's kind; social; marked by or indicating a liking for companionship; sociable; of or relating to a social group");
insert into word (word, part_id, definition) values ("halcyon", 3, "a bird identified with the kingfisher and held in ancient legend to nest at sea about the time of the winter solstice and to calm the waves during incubation");
insert into word (word, part_id, definition) values ("harangue", 3, "a speech addressed to a public assembly");
insert into word (word, part_id, definition) values ("harrow", 4, "agricultural implement with teeth drawn over plowed land to break clods of earth");
insert into word (word, part_id, definition) values ("haughty", 1, "blatantly and disdainfully proud");
insert into word (word, part_id, definition) values ("hermetic", 1, " airtight; impervious to external influence");
insert into word (word, part_id, definition) values ("hew", 4, "to cut with blows of a heavy cutting instrument");
insert into word (word, part_id, definition) values ("hirsute", 1, "hairy");
insert into word (word, part_id, definition) values ("histrionic", 1, "deliberately affected; theatrical");
insert into word (word, part_id, definition) values ("homiletics", 3, "act of preaching");
insert into word (word, part_id, definition) values ("hoodwink", 4, "to deceive by false appearance; dupe");
insert into word (word, part_id, definition) values ("hubris", 3, "exaggerated pride or self-confidence");
insert into word (word, part_id, definition) values ("iconoclast", 3, "a person who destroys religious images or opposes their veneration");
insert into word (word, part_id, definition) values ("idolatry", 3, "excessive admiration of");
insert into word (word, part_id, definition) values ("idyll", 3, "a lighthearted carefree episode; a romantic interlude");
insert into word (word, part_id, definition) values ("ignoble", 1, "of low birth or common origin; plebeian");
insert into word (word, part_id, definition) values ("ignominious", 1, "shameful dishonorable undignified disgraceful");
insert into word (word, part_id, definition) values ("imbroglio", 3, "a confused mass");
insert into word (word, part_id, definition) values ("impecunious", 1, "having very little or no money usually habitually; penniless");
insert into word (word, part_id, definition) values ("imperious", 1, "befitting or characteristic of one of eminent rank or attainments; commanding, dominant; marked by arrogant assurance; domineering");
insert into word (word, part_id, definition) values ("impiety", 3, "lack of reverence or dutifulness");
insert into word (word, part_id, definition) values ("importune", 4, "to beg persistently and urgently");
insert into word (word, part_id, definition) values ("impromptu", 3, "prompted by the occasion rather than being planned in advance; spoken, performed, done, or composed with little or no preparation; extemporaneous");
insert into word (word, part_id, definition) values ("impugned", 4, "to assail by words or arguments; oppose or attack as false or lacking integrity");
insert into word (word, part_id, definition) values ("impute", 4, "to lay the responsibility or blame for often falsely or unjustly");
insert into word (word, part_id, definition) values ("inchoate", 1, "newly begun, incomplete; not organized");
insert into word (word, part_id, definition) values ("incorrigibility", 1, "incapable of being corrected or amended; not reformable; depraved; delinquent; not manageable; unruly; unalterable, inveterate");
insert into word (word, part_id, definition) values ("inculcate", 4, "to teach and impress by frequent repetitions or admonitions");
insert into word (word, part_id, definition) values ("incursion", 3, "a hostile entrance into a territory; raid");
insert into word (word, part_id, definition) values ("indefatigability", 1, "incapable of being fatigued; untiring");
insert into word (word, part_id, definition) values ("indigence", 3, "a level of poverty in which real hardship and deprivation are suffered and comforts of life are wholly lacking");
insert into word (word, part_id, definition) values ("ineluctable", 1, "not to be avoided, changed, or resisted; inevitable");
insert into word (word, part_id, definition) values ("ingenuous", 1, "innocent; lacking in sophistication or worldliness");
insert into word (word, part_id, definition) values ("inimical", 1, "being adverse often by reason of hostility or malevolence");
insert into word (word, part_id, definition) values ("inscrutable", 1, "not readily investigated, interpreted, or understood; mysterious");
insert into word (word, part_id, definition) values ("insipid", 1, "lacking taste or savor; tasteless");
insert into word (word, part_id, definition) values ("interdict", 3, "a roman catholic ecclesiastical censure withdrawing most sacraments and christian burial from a person or district");
insert into word (word, part_id, definition) values ("intransigence", 3, "of a state refusing to compromise or to abandon an extreme position or attitude");
insert into word (word, part_id, definition) values ("intransigent", 1, "characterized by refusal to compromise or to abandon an extreme position or attitude; uncompromising");
insert into word (word, part_id, definition) values ("inundate", 4, "to cover with a flood; overflow");
insert into word (word, part_id, definition) values ("inured", 4, "made tough by habitual exposure");
insert into word (word, part_id, definition) values ("involute", 1, "curled spirally; curled or curved inward; having the edges rolled over the upper surface toward the midrib");
insert into word (word, part_id, definition) values ("irascible", 1, "marked by hot temper and easily provoked anger");
insert into word (word, part_id, definition) values ("irrevocable", 1, "not possible to revoke; unalterable");
insert into word (word, part_id, definition) values ("itinerate", 4, "to travel from place to place to peregrinate");
insert into word (word, part_id, definition) values ("jibe", 4, "to change direction while sailing downwind");
insert into word (word, part_id, definition) values ("labyrinthine", 1, "complicated; tortuous");
insert into word (word, part_id, definition) values ("lachrymose", 1, "given to tears or weeping; tearful");
insert into word (word, part_id, definition) values ("lascivious", 1, "lewd, lustful");
insert into word (word, part_id, definition) values ("lassitude", 3, "a condition of weariness or debility; fatigue");
insert into word (word, part_id, definition) values ("latent", 1, "present and capable of becoming though not now visible, obvious, active, or symptomatic");
insert into word (word, part_id, definition) values ("laudatory", 1, "expressing or giving praise");
insert into word (word, part_id, definition) values ("levee", 3, "a reception held by a person of distinction on rising from bed");
insert into word (word, part_id, definition) values ("liberality", 3, "free giving generosity");
insert into word (word, part_id, definition) values ("libertine", 3, "one who is morally unrestrained");
insert into word (word, part_id, definition) values ("lien", 3, "a charge upon real or personal property for the satisfaction of some debt or duty ordinarily arising by operation of law");
insert into word (word, part_id, definition) values ("limn", 4, "to draw or paint on a surface");
insert into word (word, part_id, definition) values ("lionize", 4, "treat as a famous person");
insert into word (word, part_id, definition) values ("loll", 4, "to hang loosely or laxly; droop");
insert into word (word, part_id, definition) values ("loquacious", 1, "full of excessive talk; wordy");
insert into word (word, part_id, definition) values ("lucubrate", 4, "write in scholarly fashion");
insert into word (word, part_id, definition) values ("luculent", 1, "clear in thought or expression; lucid");
insert into word (word, part_id, definition) values ("macerate", 4, "to cause to waste away by or as if by excessive fasting");
insert into word (word, part_id, definition) values ("machination", 3, "plot; scheme, especially an evil scheme");
insert into word (word, part_id, definition) values ("maladroit", 1, "lacking adroitness; inept");
insert into word (word, part_id, definition) values ("malapropism", 3, " the unintentional misuse of a word by confusion with one that sounds similar");
insert into word (word, part_id, definition) values ("malleable", 1, "capable of being extended or shaped by beating with a hammer or by the pressure of rollers");
insert into word (word, part_id, definition) values ("matriculation", 4, "process of admission to a group (especially a college or university)");
insert into word (word, part_id, definition) values ("maudlin", 1, "drunk enough to be emotionally silly");
insert into word (word, part_id, definition) values ("mellifluous", 1, "having a smooth rich flow");
insert into word (word, part_id, definition) values ("mendacious", 1, "given to or characterized by deception or falsehood or divergence from absolute truth");
insert into word (word, part_id, definition) values ("mendacity", 3, "dishonesty");
insert into word (word, part_id, definition) values ("mendicant", 3, " beggar");
insert into word (word, part_id, definition) values ("middling", 1, "fairly good but not very good");
insert into word (word, part_id, definition) values ("misogynist", 3, "a hatred of women");
insert into word (word, part_id, definition) values ("morose", 1, "having a sullen and gloomy disposition");
insert into word (word, part_id, definition) values ("multifarious", 1, "having or occurring in great variety; diverse");
insert into word (word, part_id, definition) values ("munificent", 1, "very liberal in giving or bestowing; lavish");
insert into word (word, part_id, definition) values ("nadir", 3, "the point of the celestial sphere that is directly opposite the zenith and vertically downward from the observer");
insert into word (word, part_id, definition) values ("neophyte", 3, "a new convert; proselyte");
insert into word (word, part_id, definition) values ("nexus", 3, "a connected group or series");
insert into word (word, part_id, definition) values ("noisome", 1, "noxious, harmful");
insert into word (word, part_id, definition) values ("nosegay", 3, "a small bunch of flowers; posy");
insert into word (word, part_id, definition) values ("nugatory", 1, "of little or no consequence; trifling, inconsequential");
insert into word (word, part_id, definition) values ("obdurate", 1, "stubbornly persistent in wrongdoing; hardened in feelings");
insert into word (word, part_id, definition) values ("obloquy", 3, "a strongly condemnatory utterance; abusive language");
insert into word (word, part_id, definition) values ("obstreperous", 1, "marked by unruly or aggressive noisiness; clamorous");
insert into word (word, part_id, definition) values ("obtrusive", 1, "projecting prominent undesirably noticeable");
insert into word (word, part_id, definition) values ("obtuse", 1, "lacking sharpness or quickness of sensibility or intellect; insensitive, stupid; difficult to comprehend; not clear or precise in thought or expression");
insert into word (word, part_id, definition) values ("obviate", 4, "to anticipate and prevent (as a situation) or make unnecessary (as an action)");
insert into word (word, part_id, definition) values ("occluded", 4, "obstructed; closed off");
insert into word (word, part_id, definition) values ("odious", 1, "arousing or deserving hatred or repugnance; hateful");
insert into word (word, part_id, definition) values ("offal", 3, "the waste or by-product of a process; trimmings of a hide; the by-products of milling used especially for stock feeds; the viscera and trimmings of a butchered animal removed in dressing; variety meat");
insert into word (word, part_id, definition) values ("officious", 1, "volunteering one's services where they are neither asked nor needed; meddlesome");
insert into word (word, part_id, definition) values ("ominous", 1, "threatening");
insert into word (word, part_id, definition) values ("onerous", 1, "involving, imposing, or constituting a burden; troublesome");
insert into word (word, part_id, definition) values ("opprobrious", 1, "showing scorn or reproach");
insert into word (word, part_id, definition) values ("ossify", 4, "to change into bone");
insert into word (word, part_id, definition) values ("ostentation", 3, "excessive display; pretentiousness");
insert into word (word, part_id, definition) values ("ostracism", 3, "shut out from society refuse to meet talk");
insert into word (word, part_id, definition) values ("overweening", 1, "arrogant, presumptuous");
insert into word (word, part_id, definition) values ("paean", 3, "a joyous song or hymn of praise, tribute, thanksgiving, or triumph");
insert into word (word, part_id, definition) values ("palate", 3, "the roof of the mouth separating the mouth from the nasal cavity");
insert into word (word, part_id, definition) values ("palatial", 1, "of, relating to, or being a palace");
insert into word (word, part_id, definition) values ("palliate", 4, "to cover by excuses and apologies");
insert into word (word, part_id, definition) values ("palpability", 1, "capable of being touched or felt; tangible");
insert into word (word, part_id, definition) values ("palpitate", 4, "to beat rapidly and strongly; throb");
insert into word (word, part_id, definition) values ("panegyric", 3, "a formal public speech delivered in high praise of a person or thing");
insert into word (word, part_id, definition) values ("pariah", 3, "a member of a low caste of southern India");
insert into word (word, part_id, definition) values ("parsimonious", 1, "too economical miserly");
insert into word (word, part_id, definition) values ("patina", 3, "a usually green film formed naturally on copper and bronze by long exposure or artificially (as by acids) and often valued aesthetically for its color; a surface appearance of something grown beautiful especially with age or use");
insert into word (word, part_id, definition) values ("paucity", 3, "smallness of number; fewness");
insert into word (word, part_id, definition) values ("peccadillo", 3, "a slight offense");
insert into word (word, part_id, definition) values ("pedantic", 1, "bookish showing off learning");
insert into word (word, part_id, definition) values ("pellucid", 1, "admitting maximum passage of light without diffusion or distortion");
insert into word (word, part_id, definition) values ("penitent", 1, "feeling or expressing humble or regretful pain or sorrow for sins or offenses; repentant");
insert into word (word, part_id, definition) values ("penurious", 1, "poor; stingy");
insert into word (word, part_id, definition) values ("penury", 3, "extreme and often niggardly frugality");
insert into word (word, part_id, definition) values ("peregrination", 4, "traveling about wandering");
insert into word (word, part_id, definition) values ("peremptory", 1, "expressive of urgency or command");
insert into word (word, part_id, definition) values ("perfidious", 1, "treacherous faithless");
insert into word (word, part_id, definition) values ("perfidy", 3, "the quality or state of being faithless or disloyal; treachery");
insert into word (word, part_id, definition) values ("perfunctory", 1, "characterized by routine or superficiality; mechanical");
insert into word (word, part_id, definition) values ("peripatetic", 3, "wandering");
insert into word (word, part_id, definition) values ("periphrastic", 1, "formed by the use of function words or auxiliaries instead of by inflection");
insert into word (word, part_id, definition) values ("perish", 4, "to become destroyed or ruined; cease to exist");
insert into word (word, part_id, definition) values ("pernicious", 1, "highly injurious or destructive; deadly");
insert into word (word, part_id, definition) values ("perspicacity", 1, "of acute mental vision or discernment; keen");
insert into word (word, part_id, definition) values ("petrous", 1, "of, relating to, or constituting the exceptionally hard and dense portion of the human temporal bone that contains the internal auditory organs");
insert into word (word, part_id, definition) values ("petulant", 1, "insolent or rude in speech or behavior");
insert into word (word, part_id, definition) values ("philistine", 3, "a smug ignorant person one who lacks knowledge");
insert into word (word, part_id, definition) values ("phlegmatic", 1, "calm sluggish temperament unemotional");
insert into word (word, part_id, definition) values ("picaresque", 1, "involving clever rogues or adventurers especially as in a type of fiction");
insert into word (word, part_id, definition) values ("pied", 4, "of mixed colors");
insert into word (word, part_id, definition) values ("pious", 1, "marked by or showing reverence for deity and devotion to divine worship; marked by conspicuous religiosity");
insert into word (word, part_id, definition) values ("piquant", 1, "engagingly stimulating or provocative");
insert into word (word, part_id, definition) values ("pith", 3, "a usually continuous central strand of spongy tissue in the stems of most vascular plants that probably functions chiefly in storage; any of various loose spongy plant tissues that resemble true pith; the soft or spongy interior of a part of the body");
insert into word (word, part_id, definition) values ("plaintive", 1, "expressive of suffering or woe; melancholy");
insert into word (word, part_id, definition) values ("platitude", 3, "the quality or state of being dull or insipid");
insert into word (word, part_id, definition) values ("pliant", 1, "easily bent, shaped, or twisted");
insert into word (word, part_id, definition) values ("plumb", 3, "a lead weight attached to a line and used to indicate a vertical direction");
insert into word (word, part_id, definition) values ("poignant", 1, "pungently pervasive");
insert into word (word, part_id, definition) values ("ponderous", 1, "of very great weight");
insert into word (word, part_id, definition) values ("portent", 3, "something that foreshadows a coming event; omen, sign");
insert into word (word, part_id, definition) values ("precepts", 3, "a command or principle intended especially as a general rule of action");
insert into word (word, part_id, definition) values ("preclude", 4, "to make impossible by necessary consequence; rule out in advance");
insert into word (word, part_id, definition) values ("predilection", 3, "an established preference for something");
insert into word (word, part_id, definition) values ("predominate", 1, "predominant");
insert into word (word, part_id, definition) values ("preen", 4, "to smooth and groom, as with birds cleaning and realigning parts of feathers using the beak");
insert into word (word, part_id, definition) values ("preponderance", 3, "greatness in number strength weight");
insert into word (word, part_id, definition) values ("preternatural", 1, "existing outside of nature");
insert into word (word, part_id, definition) values ("prevaricate", 4, "to deviate from the truth; equivocate");
insert into word (word, part_id, definition) values ("prim", 4, "to give a prim or demure expression to");
insert into word (word, part_id, definition) values ("proclivity", 3, "a natural inclination");
insert into word (word, part_id, definition) values ("profligacy", 3, "shameless immorality");
insert into word (word, part_id, definition) values ("profundity", 3, "intellectual depth; something profound or abstruse");
insert into word (word, part_id, definition) values ("profuse", 1, "pouring forth liberally; extravagant");
insert into word (word, part_id, definition) values ("prolix", 1, "unduly prolonged or drawn out; too long");
insert into word (word, part_id, definition) values ("propitious", 1, "favorably disposed; benevolent");
insert into word (word, part_id, definition) values ("prosaic", 1, "characteristic of prose as distinguished from poetry; factual; dull, unimaginative");
insert into word (word, part_id, definition) values ("proscribe", 4, "to publish the name of as condemned to death with the property of the condemned forfeited to the state");
insert into word (word, part_id, definition) values ("provident", 1, "making provision for the future; prudent");
insert into word (word, part_id, definition) values ("provisional", 1, "of the present time only");
insert into word (word, part_id, definition) values ("prune", 3, "a plum dried or capable of drying without fermentation");
insert into word (word, part_id, definition) values ("pucker", 4, "to draw up into folds or wrinkles");
insert into word (word, part_id, definition) values ("pugnacious", 1, "having a quarrelsome or combative nature; truculent");
insert into word (word, part_id, definition) values ("puissance", 3, "strength, power");
insert into word (word, part_id, definition) values ("punctilious", 1, "precise paying attention to trivialities");
insert into word (word, part_id, definition) values ("pungency", 3, "sharpness stinging quality");
insert into word (word, part_id, definition) values ("pusillanimous", 1, "lacking courage and resolution; marked by contemptible timidity");
insert into word (word, part_id, definition) values ("putrefaction", 3, "the state of being putrefied; corruption");
insert into word (word, part_id, definition) values ("quaff", 4, "to drink heartily, or a hearty draught");
insert into word (word, part_id, definition) values ("qualm", 3, "a sudden attack of illness, faintness, or nausea");
insert into word (word, part_id, definition) values ("quell", 4, "to thoroughly overwhelm and reduce to submission or passivity");
insert into word (word, part_id, definition) values ("quiescence", 3, "state of being passive or motionless");
insert into word (word, part_id, definition) values ("quiescent", 1, "marked by inactivity or repose; tranquilly at rest");
insert into word (word, part_id, definition) values ("quixotic", 1, "capricious, unpredictable");
insert into word (word, part_id, definition) values ("quotidian", 1, "occurring every day");
insert into word (word, part_id, definition) values ("rabble", 3, "a disorganized or confused collection of things");
insert into word (word, part_id, definition) values ("raconteur", 3, "a person who excels in telling anecdotes");
insert into word (word, part_id, definition) values ("rancorous", 1, "feeling bitterness spitefulness");
insert into word (word, part_id, definition) values ("rapacious", 1, "excessively grasping or covetous");
insert into word (word, part_id, definition) values ("rebuff", 4, "to reject or criticize sharply; snub");
insert into word (word, part_id, definition) values ("recalcitrant", 1, "obstinately defiant of authority or restraint");
insert into word (word, part_id, definition) values ("recidivism", 3, "relapse into antisocial or criminal behavior");
insert into word (word, part_id, definition) values ("reciprocity", 3, "granting of privileges in return for similar");
insert into word (word, part_id, definition) values ("recompense", 4, "to give something to by way of compensation (as for a service rendered or damage incurred); to pay for");
insert into word (word, part_id, definition) values ("recondite", 1, "hidden from sight; concealed");
insert into word (word, part_id, definition) values ("redoubtable", 1, "causing fear or alarm; formidable");
insert into word (word, part_id, definition) values ("refractory", 1, "resisting control or authority; stubborn, unmanageable");
insert into word (word, part_id, definition) values ("refulgent", 3, "a radiant or resplendent quality or state; brilliance");
insert into word (word, part_id, definition) values ("regale", 4, "to entertain sumptuously; feast with delicacies");
insert into word (word, part_id, definition) values ("remonstrate", 4, "argue in protest or opposition");
insert into word (word, part_id, definition) values ("repast", 3, "something taken as food; meal");
insert into word (word, part_id, definition) values ("reprobate", 4, "to condemn strongly as unworthy, unacceptable, or evil");
insert into word (word, part_id, definition) values ("repudiate", 4, "to divorce or separate formally from");
insert into word (word, part_id, definition) values ("requite", 4, "to make return for; repay; to make retaliation for; avenge");
insert into word (word, part_id, definition) values ("rescind", 4, "to take away; remove");
insert into word (word, part_id, definition) values ("reticent", 1, "inclined to be silent or uncommunicative in speech; reserved");
insert into word (word, part_id, definition) values ("sagacious", 1, "of keen and farsighted penetration and judgment; discerning; caused by or indicating acute discernment");
insert into word (word, part_id, definition) values ("salubrious", 1, "favorable to or promoting health or well-being");
insert into word (word, part_id, definition) values ("sanctimony", 3, "affected or hypocritical holiness");
insert into word (word, part_id, definition) values ("sanguine", 1, "confidently optimistic and cheerful; blood-red in color");
insert into word (word, part_id, definition) values ("satiate", 1, "satisfy fully");
insert into word (word, part_id, definition) values ("saturnine", 1, "cold and steady in mood; slow to act or change; gloomy; dark; sullen; morose");
insert into word (word, part_id, definition) values ("scorn", 3, "open dislike and disrespect or derision often mixed with indignation");
insert into word (word, part_id, definition) values ("scurvy", 3, "a disease caused by a lack of vitamin C and characterized by spongy gums, loosening of the teeth, and a bleeding into the skin and mucous membranes");
insert into word (word, part_id, definition) values ("sedulous", 1, "involving or accomplished with careful perseverance");
insert into word (word, part_id, definition) values ("sententious", 1, "given to or abounding in aphoristic expression; given to or abounding in excessive moralizing");
insert into word (word, part_id, definition) values ("sere", 1, "being dried and withered");
insert into word (word, part_id, definition) values ("serration", 3, "having a toothed edge");
insert into word (word, part_id, definition) values ("shunt", 4, "to turn off to one side; shift; to switch (as a train) from one track to another");
insert into word (word, part_id, definition) values ("simper", 4, "a silly self-conscious smile");
insert into word (word, part_id, definition) values ("skiff", 3, "a small flat-bottomed open boat with a pointed bow and square stern, used mainly by fisherman");
insert into word (word, part_id, definition) values ("slake", 4, "to become slaked; crumble");
insert into word (word, part_id, definition) values ("smolder", 4, "to exist in a state of suppressed activity");
insert into word (word, part_id, definition) values ("somatic", 1, "of, relating to, or affecting the body especially as distinguished from the germplasm or the psyche");
insert into word (word, part_id, definition) values ("sophomoric", 1, "self-assured though immature affected bombastic overblown");
insert into word (word, part_id, definition) values ("soporific", 1, "causing or tending to cause sleep; tending to dull awareness or alertness");
insert into word (word, part_id, definition) values ("sordid", 1, "marked by baseness or grossness; vile");
insert into word (word, part_id, definition) values ("specious", 1, "having deceptive attraction or allure");
insert into word (word, part_id, definition) values ("spurious", 1, "of illegitimate birth; bastard");
insert into word (word, part_id, definition) values ("stanch", 4, "to stop or check in its course; to make watertight; stop up");
insert into word (word, part_id, definition) values ("stentorian", 1, "extremely loud and powerful");
insert into word (word, part_id, definition) values ("stipple", 4, "to engrave by means of dots and flicks");
insert into word (word, part_id, definition) values ("stolid", 1, "having or expressing little or no sensibility; unemotional");
insert into word (word, part_id, definition) values ("stormy", 1, "marked by turmoil or fury");
insert into word (word, part_id, definition) values ("striated", 4, "striped grooved or banded");
insert into word (word, part_id, definition) values ("strident", 1, "blatant: conspicuously and offensively loud; given to vehement outcry");
insert into word (word, part_id, definition) values ("strut", 4, "to become turgid; swell");
insert into word (word, part_id, definition) values ("suborn", 4, "to induce secretly to do an unlawful thing");
insert into word (word, part_id, definition) values ("subsume", 4, "to include or place within something larger or more comprehensive; encompass as a subordinate or component element");
insert into word (word, part_id, definition) values ("succor", 3, "something that furnishes relief");
insert into word (word, part_id, definition) values ("summarily", 1, "done without delay or formality; quickly executed; of, relating to, or using a summary proceeding");
insert into word (word, part_id, definition) values ("sumptuous", 1, "deluxe: rich and superior in quality");
insert into word (word, part_id, definition) values ("superfluous", 1, "exceeding what is sufficient or necessary; extra; not needed; unnecessary");
insert into word (word, part_id, definition) values ("supersede", 4, "to cause to be set aside; to force out of use as inferior");
insert into word (word, part_id, definition) values ("supine", 3, "lying flat on back, with face upward");
insert into word (word, part_id, definition) values ("suppliant", 3, "petitioner: one praying humbly for something");
insert into word (word, part_id, definition) values ("supplicate", 4, "to ask humbly and earnestly of");
insert into word (word, part_id, definition) values ("sycophant", 3, "a servile self-seeking flatterer");
insert into word (word, part_id, definition) values ("taciturn", 1, "temperamentally disinclined to talk");
insert into word (word, part_id, definition) values ("tangential", 1, "suddenly changeable");
insert into word (word, part_id, definition) values ("tassel", 3, "a dangling ornament made by laying parallel a bunch of cords or threads of even length and fastening them at one end");
insert into word (word, part_id, definition) values ("taut", 1, "having no give or slack; tightly drawn; high-strung, tense");
insert into word (word, part_id, definition) values ("tautology", 3, "needless repetition of an idea, statement, or word; an instance of tautology");
insert into word (word, part_id, definition) values ("tawdry", 1, "brassy; tastelessly showy");
insert into word (word, part_id, definition) values ("teetotal", 1, "of, relating to, or practicing teetotalism");
insert into word (word, part_id, definition) values ("temerity", 3, "unreasonable or foolhardy contempt of danger or opposition; rashness, recklessness");
insert into word (word, part_id, definition) values ("tepid", 1, "moderately warm; lukewarm");
insert into word (word, part_id, definition) values ("timorous", 1, "of a timid disposition; fearful");
insert into word (word, part_id, definition) values ("torpid", 1, "having lost motion or the power of exertion or feeling; dormant, numb; sluggish in functioning or acting");
insert into word (word, part_id, definition) values ("tout", 4, "to spy on; watch");
insert into word (word, part_id, definition) values ("transgress", 4, "to violate a command or law; sin");
insert into word (word, part_id, definition) values ("transitory", 1, "tending to pass away; not persistent");
insert into word (word, part_id, definition) values ("trenchant", 1, "keen, sharp");
insert into word (word, part_id, definition) values ("trite", 1, "hackneyed or boring from much use; not fresh or original");
insert into word (word, part_id, definition) values ("truculent", 1, "feeling or displaying ferocity; cruel, savage");
insert into word (word, part_id, definition) values ("turbid", 1, "thick or opaque with or as if with roiled sediment; heavy with smoke or mist");
insert into word (word, part_id, definition) values ("turgid", 1, "excessively embellished in style or language; bombastic, pompous");
insert into word (word, part_id, definition) values ("tyro", 3, "beginner");
insert into word (word, part_id, definition) values ("ubiquitous", 1, "present everywhere");
insert into word (word, part_id, definition) values ("umbrage", 3, "shade, shadow");
insert into word (word, part_id, definition) values ("undulate", 1, "having a wavy surface, edge, or markings");
insert into word (word, part_id, definition) values ("upbraid", 4, "to criticize severely; find fault with");
insert into word (word, part_id, definition) values ("urbane", 1, "notably polite or polished in manner");
insert into word (word, part_id, definition) values ("vacillation", 3, "being uncertain hesitating");
insert into word (word, part_id, definition) values ("vagary", 3, "an erratic, unpredictable, or extravagant manifestation, action, or notion");
insert into word (word, part_id, definition) values ("veer", 4, "to let out (as a rope)");
insert into word (word, part_id, definition) values ("venal", 1, "originating in, characterized by, or associated with corrupt bribery");
insert into word (word, part_id, definition) values ("veneration", 3, "regard with deep respect");
insert into word (word, part_id, definition) values ("veracity", 3, "truth");
insert into word (word, part_id, definition) values ("verdant", 1, "green in tint or color; green with growing plants");
insert into word (word, part_id, definition) values ("verisimilitude", 3, "the quality or state of being verisimilar");
insert into word (word, part_id, definition) values ("veritable", 1, "being in fact the thing named and not false, unreal, or imaginary -- often used to stress the aptness of a metaphor");
insert into word (word, part_id, definition) values ("vestige", 3, "a trace, mark, or visible sign left by something (as an ancient city or a condition or practice) vanished or lost; the smallest quantity or trace; footprint");
insert into word (word, part_id, definition) values ("vilify", 4, "to lower in estimation or importance");
insert into word (word, part_id, definition) values ("virago", 3, "a loud overbearing woman; termagant");
insert into word (word, part_id, definition) values ("vitiate", 4, "to make faulty or defective; impair");
insert into word (word, part_id, definition) values ("vivacious", 1, "lively in temper, conduct, or spirit; sprightly");
insert into word (word, part_id, definition) values ("volubility", 1, "easily rolling or turning; rotating");
insert into word (word, part_id, definition) values ("waft", 4, "to be driven or carried along, as by the air");
insert into word (word, part_id, definition) values ("welter", 4, "to become deeply sunk, soaked, or involved");
insert into word (word, part_id, definition) values ("writ", 3, "something written; writing");
